### ISSUE TITLE
Redis 7 support

### ISSUE THREAD

**Issue by chrillep** [lando/redis#12]
- https://hub.docker.com/_/redis
- https://github.com/docker-library/redis/tree/master/7.0

**Comment by reynoldsalec** [comment]
Thanks for taking this on @Alexj12 and for putting up the PR!

I just merged your work, cut a new release of the Redis plugin, and added it to [`lando-cli`](https://github.com/lando/cli/commit/9df055c6692b49e521c91a0b5334b54b3e99b63d), so it'll be available in the next release of Lando, which I believe @pirog will cut tomorrow (April 7th).

In the meantime, you should be able to install the new version of the Redis plugin globally on your computer.

Thanks again, appreciate the contribution :)

**Comment by Alexj12** [comment]
Thanks @reynoldsalec!
